### ISSUE TITLE
Build fails on macOS (arm64)

### ISSUE THREAD

**Issue by timcraft** [seven1m/natalie#82] opened 2021-08-25 16:02 UTC
Cool project!

Unfortunately when I try to build from source I get the following errors:

<details><pre><code>[  6%] Building CXX object CMakeFiles/natalie-base.dir/src/fiber_value.cpp.o
&lt;inline asm&gt;:3:8: error: unexpected token in argument list
        mov 12(%esp), %eax
              ^
&lt;inline asm&gt;:4:7: error: unexpected token in argument list
        mov 8(%esp), %ecx
             ^
&lt;inline asm&gt;:5:7: error: unexpected token in argument list
        mov 4(%esp), %edx
             ^
&lt;inline asm&gt;:6:7: error: unknown token in expression
        push %ebx
             ^
&lt;inline asm&gt;:6:7: error: invalid operand
        push %ebx
             ^
&lt;inline asm&gt;:7:7: error: unknown token in expression
        push %ebp
             ^
&lt;inline asm&gt;:7:7: error: invalid operand
        push %ebp
             ^
&lt;inline asm&gt;:8:7: error: unknown token in expression
        push %esi
             ^
&lt;inline asm&gt;:8:7: error: invalid operand
        push %esi
             ^
&lt;inline asm&gt;:9:7: error: unknown token in expression
        push %edi
             ^
&lt;inline asm&gt;:9:7: error: invalid operand
        push %edi
             ^
&lt;inline asm&gt;:10:6: error: unknown token in expression
        mov %esp, (%ecx)
            ^
&lt;inline asm&gt;:10:6: error: invalid operand
        mov %esp, (%ecx)
            ^
&lt;inline asm&gt;:11:7: error: unknown token in expression
        mov (%edx), %esp
             ^
&lt;inline asm&gt;:11:6: error: invalid operand
        mov (%edx), %esp
            ^
&lt;inline asm&gt;:12:6: error: unknown token in expression
        pop %edi
            ^
&lt;inline asm&gt;:12:6: error: invalid operand
        pop %edi
            ^
&lt;inline asm&gt;:13:6: error: unknown token in expression
        pop %esi
            ^
&lt;inline asm&gt;:13:6: error: invalid operand
        pop %esi
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[4]: *** [CMakeFiles/natalie-base.dir/src/fiber_value.cpp.o] Error 1
make[3]: *** [CMakeFiles/natalie-base.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [build_debug] Error 2
make: *** [build] Error 2</code></pre></details>

Is there an alternative to `fiber_value.*` that supports arm64?

**Comment by TheGrizzlyDev** [comment] 2021-08-30 16:54
I am able to reproduce the same issue on linux on arm64 using https://github.com/multiarch/qemu-user-static. SInce this runs on docker I will try to automate it for the CI (if gh-actions allows me to do that :) ) and then try and fix the issue. @seven1m what do you think about this?

**Comment by seven1m** [comment] 2021-08-30 16:56
Yeah if you want to give it a shot, go for it! Getting the calling convention correct in the assembly code would be the hardest part I think... 🤔

**Comment by seven1m** [comment] 2021-11-20 21:17
Fixed in #259

**Closed by seven1m** 2021-11-20 21:17 UTC
Labels: bug

**Comment by timcraft** [comment] 2021-11-22 11:42
@seven1m Awesome, thank you! Building from source and `rake test` work as expected.
